### ISSUE TITLE
Chef::Exceptions::CookbookNotFound: Cookbook java not found.

### ISSUE THREAD

**Issue by dsuch** [calebgroom/vagrant-cassandra#5]
Hello,

I'm just reporting that I cannot install the box using the instructions provided - it seems a chef cookbook java is not found.

I'm not familiar with chef really but I understand it's akin to one of the dependencies not being available.

Cheers!

```
$ vagrant up
Bringing machine 'node1' up with 'virtualbox' provider...
Bringing machine 'node2' up with 'virtualbox' provider...
Bringing machine 'node3' up with 'virtualbox' provider...
[node1] Box 'precise' was not found. Fetching box from specified URL for
the provider 'virtualbox'. Note that if the URL does not have
a box for this provider, you should interrupt Vagrant now and add
the box yourself. Otherwise Vagrant will attempt to download the
full box prior to discovering this error.
Downloading box from URL: http://files.vagrantup.com/precise64.box
Extracting box...te: 1219k/s, Estimated time remaining: 0:00:01)
Successfully added box 'precise' with provider 'virtualbox'!
[node1] Importing base box 'precise'...
[node1] Matching MAC address for NAT networking...
[node1] Setting the name of the VM...
[node1] Clearing any previously set forwarded ports...
[node1] The cookbook path '/media/160/data/install/vagrant-cassandra/vagrant/cookbooks' doesn't exist. Ignoring...
[node1] Clearing any previously set network interfaces...
[node1] Preparing network interfaces based on configuration...
[node1] Forwarding ports...
[node1] -- 22 => 2222 (adapter 1)
[node1] Booting VM...
[node1] Waiting for machine to boot. This may take a few minutes...
[node1] Machine booted and ready!
[node1] The guest additions on this VM do not match the installed version of
VirtualBox! In most cases this is fine, but in rare cases it can
prevent things such as shared folders from working properly. If you see
shared folder errors, please make sure the guest additions within the
virtual machine match the version of VirtualBox you have installed on
your host and reload your VM.

Guest Additions Version: 4.2.0
VirtualBox Version: 4.3
[node1] Setting hostname...
[node1] Configuring and enabling network interfaces...
[node1] Mounting shared folders...
[node1] -- /vagrant
[node1] -- /tmp/vagrant-chef-1/chef-solo-1/cookbooks
[node1] Running provisioner: shell...
[node1] Running: inline script
stdin: is not a tty
Successfully installed mixlib-config-2.1.0
Successfully installed mixlib-cli-1.3.0
Successfully installed mixlib-shellout-1.4.0
Successfully installed net-ssh-2.9.1
Successfully installed chef-11.4.2
5 gems installed
[node1] Running provisioner: chef_solo...
Generating chef JSON and uploading...
Running chef-solo...
stdin: is not a tty
[2014-06-20T16:57:43+00:00] INFO: *** Chef 11.4.2 ***
[2014-06-20T16:57:44+00:00] DEBUG: Building node object for node1
[2014-06-20T16:57:44+00:00] DEBUG: Extracting run list from JSON attributes provided on command line
[2014-06-20T16:57:44+00:00] INFO: Setting the run_list to ["recipe[updater]", "recipe[java]", "recipe[cassandra::tarball]"] from JSON
[2014-06-20T16:57:44+00:00] DEBUG: Applying attributes from json file
[2014-06-20T16:57:44+00:00] DEBUG: Platform is ubuntu version 12.04
[2014-06-20T16:57:44+00:00] INFO: Run List is [recipe[updater], recipe[java], recipe[cassandra::tarball]]
[2014-06-20T16:57:44+00:00] INFO: Run List expands to [updater, java, cassandra::tarball]
[2014-06-20T16:57:44+00:00] INFO: Starting Chef Run for node1
[2014-06-20T16:57:44+00:00] INFO: Running start handlers
[2014-06-20T16:57:44+00:00] INFO: Start handlers complete.
[2014-06-20T16:57:44+00:00] DEBUG: No chefignore file found at /tmp/vagrant-chef-1/chef-solo-1/cookbooks/chefignore no files will be ignored
[2014-06-20T16:57:44+00:00] DEBUG: Re-raising exception: Chef::Exceptions::CookbookNotFound - Cookbook java not found. If you're loading java from another cookbook, make sure you configure the dependency in your metadata
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-11.4.2/bin/../lib/chef/cookbook/cookbook_collection.rb:38:in `initialize'
  /opt/vagrant_ruby/lib/ruby/gems/1.8/gems/ohai-6.14.0/lib/ohai/mash.rb:77:in `call'
  /opt/vagrant_ruby/lib/ruby/gems/1.8/gems/ohai-6.14.0/lib/ohai/mash.rb:77:in `default'
  /opt/vagrant_ruby/lib/ruby/gems/1.8/gems/ohai-6.14.0/lib/ohai/mash.rb:77:in `default'
  /opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-11.4.2/bin/../lib/chef/run_context/cookbook_compiler.rb:265:in `[]'
  /opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-11.4.2/bin/../lib/chef/run_context/cookbook_compiler.rb:265:in `each_cookbook_dep'
  /opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-11.4.2/bin/../lib/chef/run_context/cookbook_compiler.rb:243:in `add_cookbook_with_deps'
  /opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-11.4.2/bin/../lib/chef/run_context/cookbook_compiler.rb:87:in `cookbook_order'
  /opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-11.4.2/bin/../lib/chef/run_context/cookbook_compiler.rb:85:in `each'
  /opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-11.4.2/bin/../lib/chef/run_context/cookbook_compiler.rb:85:in `cookbook_order'
  /opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-11.4.2/bin/../lib/chef/run_context/cookbook_compiler.rb:97:in `compile_libraries'
  /opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-11.4.2/bin/../lib/chef/run_context/cookbook_compiler.rb:70:in `compile'
  /opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-11.4.2/bin/../lib/chef/run_context.rb:86:in `load'
  /opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-11.4.2/bin/../lib/chef/client.rb:224:in `setup_run_context'
  /opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-11.4.2/bin/../lib/chef/client.rb:467:in `do_run'
  /opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-11.4.2/bin/../lib/chef/client.rb:200:in `run'
  /opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-11.4.2/bin/../lib/chef/application.rb:190:in `run_chef_client'
  /opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-11.4.2/bin/../lib/chef/application/solo.rb:239:in `run_application'
  /opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-11.4.2/bin/../lib/chef/application/solo.rb:231:in `loop'
  /opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-11.4.2/bin/../lib/chef/application/solo.rb:231:in `run_application'
  /opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-11.4.2/bin/../lib/chef/application.rb:73:in `run'
  /opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-11.4.2/bin/chef-solo:25
  /opt/vagrant_ruby/bin/chef-solo:19:in `load'
  /opt/vagrant_ruby/bin/chef-solo:19
[2014-06-20T16:57:44+00:00] ERROR: Running exception handlers
[2014-06-20T16:57:44+00:00] ERROR: Exception handlers complete
[2014-06-20T16:57:44+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2014-06-20T16:57:44+00:00] DEBUG: Chef::Exceptions::CookbookNotFound: Cookbook java not found. If you're loading java from another cookbook, make sure you configure the dependency in your metadata
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-11.4.2/bin/../lib/chef/cookbook/cookbook_collection.rb:38:in `initialize'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/ohai-6.14.0/lib/ohai/mash.rb:77:in `call'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/ohai-6.14.0/lib/ohai/mash.rb:77:in `default'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/ohai-6.14.0/lib/ohai/mash.rb:77:in `default'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-11.4.2/bin/../lib/chef/run_context/cookbook_compiler.rb:265:in `[]'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-11.4.2/bin/../lib/chef/run_context/cookbook_compiler.rb:265:in `each_cookbook_dep'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-11.4.2/bin/../lib/chef/run_context/cookbook_compiler.rb:243:in `add_cookbook_with_deps'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-11.4.2/bin/../lib/chef/run_context/cookbook_compiler.rb:87:in `cookbook_order'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-11.4.2/bin/../lib/chef/run_context/cookbook_compiler.rb:85:in `each'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-11.4.2/bin/../lib/chef/run_context/cookbook_compiler.rb:85:in `cookbook_order'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-11.4.2/bin/../lib/chef/run_context/cookbook_compiler.rb:97:in `compile_libraries'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-11.4.2/bin/../lib/chef/run_context/cookbook_compiler.rb:70:in `compile'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-11.4.2/bin/../lib/chef/run_context.rb:86:in `load'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-11.4.2/bin/../lib/chef/client.rb:224:in `setup_run_context'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-11.4.2/bin/../lib/chef/client.rb:467:in `do_run'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-11.4.2/bin/../lib/chef/client.rb:200:in `run'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-11.4.2/bin/../lib/chef/application.rb:190:in `run_chef_client'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-11.4.2/bin/../lib/chef/application/solo.rb:239:in `run_application'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-11.4.2/bin/../lib/chef/application/solo.rb:231:in `loop'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-11.4.2/bin/../lib/chef/application/solo.rb:231:in `run_application'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-11.4.2/bin/../lib/chef/application.rb:73:in `run'
/opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-11.4.2/bin/chef-solo:25
/opt/vagrant_ruby/bin/chef-solo:19:in `load'
/opt/vagrant_ruby/bin/chef-solo:19
[2014-06-20T16:57:44+00:00] FATAL: Chef::Exceptions::CookbookNotFound: Cookbook java not found. If you're loading java from another cookbook, make sure you configure the dependency in your metadata
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
$
```

**Comment by ghost** [comment]
@dsuch Have you resolved this issue?
